services:
  pytorch:
    container_name: pytorch-container

    build:
      context: .
      dockerfile: Dockerfile

    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    environment:
      - PYTHONUNBUFFERED=1

    ports:
      - "8080:8080"
    volumes:
      - .:/app
    stdin_open: true
    tty: true
    networks:
      - main-network

  pyramid:
    container_name: pyramid-container

    build:
      context: .
      dockerfile: ./pyramid/Dockerfile

    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    environment:
      - PYTHONUNBUFFERED=1

    volumes:
      - ./pyramid:/app/src
    stdin_open: true
    tty: true
    networks:
      - main-network

networks:
  main-network:
    driver: bridge
